#!/usr/bin/env bash
# Install (once) and start the internal Label Studio service for OCR-IDS.
set -euo pipefail

PROJECT_ROOT="${OCR_IDS_REMOTE_PROJECT:-/home/hzh/ocr_ids}"
RUNTIME_ROOT="${OCR_IDS_REMOTE_RUNTIME:-/home/hzh/ocr_ids_runtime}"
UV_BIN="${UV_BIN:-$HOME/.local/bin/uv}"
LABEL_STUDIO_ROOT="${OCR_IDS_LABEL_STUDIO_ROOT:-$RUNTIME_ROOT/label-studio}"
LABEL_STUDIO_PORT="${LABEL_STUDIO_PORT:-8082}"

if [[ ! -x "$UV_BIN" ]]; then
  echo "uv is required at $UV_BIN (set UV_BIN to override)" >&2
  exit 2
fi

mkdir -p "$LABEL_STUDIO_ROOT"
if [[ ! -x "$LABEL_STUDIO_ROOT/.venv/bin/label-studio" ]]; then
  "$UV_BIN" venv "$LABEL_STUDIO_ROOT/.venv"
  "$UV_BIN" pip install --python "$LABEL_STUDIO_ROOT/.venv/bin/python" label-studio
fi

# Images remain on the lab server.  Label Studio receives only local-file URLs
# generated by create_label_studio_tasks.py; no image corpus is copied locally.
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
export LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT="$RUNTIME_ROOT/datasets"

cd "$PROJECT_ROOT"
exec "$LABEL_STUDIO_ROOT/.venv/bin/label-studio" start \
  --host 0.0.0.0 --port "$LABEL_STUDIO_PORT" --data-dir "$LABEL_STUDIO_ROOT/data"
